#!/bin/sh
### BEGIN INIT INFO
# Provides:          shairport
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to start shairport
# Description:       Service script for shairport, command line airplay device
### END INIT INFO

USER=$(grep -a "SYSTEM_USER" /opt/max2play/audioplayer.conf | sed -n -e 's/^[A-Z_]*\=//p')
if [ "$USER" = "" ]; then
    USER=odroid
elif [ "$USER" = "pi" ]; then
	# Environment variable not set in cron or from other user running as sudo -> important for pulseaudio (bluetooth on jessie)
	export XDG_RUNTIME_DIR=/run/user/1000
fi
NAME=$(cat /opt/max2play/playername.txt)
SHAIRPORT_PARAMETER=$(grep -a "SHAIRPORT_PARAMETER" /opt/max2play/audioplayer.conf | sed -n -e 's/^[A-Z_]*\=//p')

LMSIP=$(grep -a "LMSIP" /opt/max2play/audioplayer.conf | sed -n -e 's/^[A-Z_]*\=//p')
if [ ! "$LMSIP" = "" ]; then
    SHAIRPORT_OPTIONS="--on-start '/opt/max2play/shairport_switch.sh shutup' --on-stop '/opt/max2play/shairport_switch.sh resume'"
else
	SHAIRPORT_OPTIONS=""
fi

case "$1" in
  start)
    echo "Starting Shairport"
    echo "Check auf laufenden XBMC - Pulseaudio VS Alsa bringt Probleme"
    xbmcrunning=$(ps -Al | grep xbmc | wc -l)
    if [ "1" -gt "$xbmcrunning" ]
    then
	  # -d plug:plugequal for Equalizer Options
	  # /sbin/start-stop-daemon --start --quiet -b -m -p /opt/shairport/log/shairport.pid --chuid $USER --exec /opt/shairport/shairport -- --name "$NAME" -o alsa -- $SHAIRPORT_PARAMETER
      /sbin/start-stop-daemon --start -b -m -p /tmp/shairport.pid --chuid $USER --startas /bin/bash -- -c "exec /opt/shairport/shairport --name \"$NAME\" -o alsa $SHAIRPORT_OPTIONS -- $SHAIRPORT_PARAMETER > /tmp/shairport.txt 2>&1"      
    fi
  ;;
  stop)
    echo "Stopping Shairport"
    /sbin/start-stop-daemon --stop --quiet --pidfile /tmp/shairport.pid
    rm -f /tmp/shairport.pid
  ;;
  *)
    echo "Usage: /etc/init.d/shairport {start|stop}"
    exit 1
  ;;
esac
exit 0
